name: new-normal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - jupyter=1.1.1
  - plotly=6.3.0
  - pandas=2.3.3
  - scikit-learn=1.7.2
  - rtree=1.4.1
  - pyproj=3.7.2
  - geopandas=1.1.1
  - numpy=2.3.5
  - shapely=2.1.2
  - fiona=1.10.1
  - seaborn=0.13.2
  - gdal=3.10.3
  - pillow=11.3.0